package dev.robgro.timesheet.invoice;

import dev.robgro.timesheet.exception.ValidationException;
import lombok.Value;

/**
 * Immutable value object representing a generated invoice number with its components.
 * Used as return type from InvoiceNumberGenerator to provide all necessary data
 * for storing invoice number in component-based format.
 */
@Value
public class GeneratedInvoiceNumber {
    /**
     * Sequence number within the period (e.g., 1, 2, 3...)
     * Always starts from 1 when period resets
     */
    Integer sequenceNumber;

    /**
     * Year component for sorting and reset logic (e.g., 2026)
     * Always populated regardless of reset period
     */
    Integer periodYear;

    /**
     * Month component for MONTHLY reset periods (1-12)
     * CRITICAL: Must be 0 (not NULL) for YEARLY/NEVER reset periods
     * to avoid UNIQUE constraint issues in MariaDB where NULL != NULL
     */
    Integer periodMonth;

    /**
     * Human-readable formatted invoice number (e.g., "001-01-2026", "INV-123-2024")
     * Generated by applying template to components
     */
    String displayNumber;

    /**
     * ID of the numbering scheme that generated this number.
     * Stored on the invoice for audit trail: "which scheme produced this number?"
     * Null only for peek/preview operations where scheme lookup is skipped.
     */
    Long schemeId;

    /**
     * Creates new GeneratedInvoiceNumber with validation.
     * Validates all components to ensure data integrity.
     *
     * @param sequenceNumber Must be >= 1
     * @param periodYear Required (cannot be null)
     * @param periodMonth Must be 0-12 (0 for YEARLY/NEVER, 1-12 for MONTHLY)
     * @param displayNumber Required non-blank string
     * @param schemeId ID of the scheme that generated this number (null for previews)
     * @throws ValidationException if any validation fails
     */
    public GeneratedInvoiceNumber(
        Integer sequenceNumber,
        Integer periodYear,
        Integer periodMonth,
        String displayNumber,
        Long schemeId
    ) {
        if (sequenceNumber == null || sequenceNumber < 1) {
            throw new ValidationException("Sequence number must be >= 1, got: " + sequenceNumber);
        }
        if (periodYear == null) {
            throw new ValidationException("Period year is required");
        }
        if (periodMonth == null || periodMonth < 0 || periodMonth > 12) {
            throw new ValidationException(
                "Period month must be 0-12 (0=yearly/never, 1-12=monthly), got: " + periodMonth
            );
        }
        if (displayNumber == null || displayNumber.isBlank()) {
            throw new ValidationException("Display number is required and cannot be blank");
        }

        this.sequenceNumber = sequenceNumber;
        this.periodYear = periodYear;
        this.periodMonth = periodMonth;
        this.displayNumber = displayNumber;
        this.schemeId = schemeId;
    }
}
